package com.alipay.oceanbase;

import java.io.InputStream;
import java.io.Reader;
import java.math.BigDecimal;
import java.net.URL;
import java.sql.Array;
import java.sql.Blob;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.Date;
import java.sql.NClob;
import java.sql.ParameterMetaData;
import java.sql.PreparedStatement;
import java.sql.Ref;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.RowId;
import java.sql.SQLException;
import java.sql.SQLXML;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.Calendar;
import java.util.Collection;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;

import org.apache.log4j.Logger;

import com.alipay.oceanbase.factory.DataSourceHolder;
import com.alipay.oceanbase.group.MergeServerSelector.DataSourceTryer;
import com.alipay.oceanbase.jdbc.parameter.ParameterContext;
import com.alipay.oceanbase.jdbc.parameter.ParameterMethod;
import com.alipay.oceanbase.jdbc.parameter.Parameters;
import com.alipay.oceanbase.util.parse.SQLHintParser;
import com.alipay.oceanbase.util.parse.SQLParser;
import com.alipay.oceanbase.util.parse.SqlHintType;
import com.alipay.oceanbase.util.parse.SqlType;

/**
 * 
 * 
 * @author liangjie.li
 * @version $Id: TGroupPreparedStatement.java, v 0.1 2013-5-24 下午4:13:47 liangjie.li Exp $
 */
public class TGroupPreparedStatement extends TGroupStatement implements PreparedStatement {

    private static final Logger logger = Logger.getLogger(TGroupPreparedStatement.class);

    private String              sql    = null;

    public TGroupPreparedStatement(OBGroupDataSource tGroupDataSource,
                                   TGroupConnection tGroupConnection, String sql) {
        super(tGroupDataSource, tGroupConnection);
        this.sql = sql;
    }

    private int                              autoGeneratedKeys = -1;
    private int[]                            columnIndexes     = null;
    private String[]                         columnNames       = null;

    protected Map<Integer, ParameterContext> parameterSettings = new LinkedHashMap<Integer, ParameterContext>();

    public void clearParameters() throws SQLException {
        parameterSettings.clear();
    }

    private PreparedStatement baseStatement = null;

    void setBaseStatement(PreparedStatement baseStatement) {
        this.baseStatement = baseStatement;
    }

    private PreparedStatement createPreparedStatementInternal(Connection conn, String sql)
                                                                                          throws SQLException {
        if (this.baseStatement != null) {
            try {
                this.baseStatement.close();
            } catch (SQLException e) {
                logger.error("close baseStatement failed.", e);
            }
        }

        PreparedStatement ps = null;

        if (autoGeneratedKeys != -1) {
            ps = conn.prepareStatement(sql, autoGeneratedKeys);
        } else if (columnIndexes != null) {
            ps = conn.prepareStatement(sql, columnIndexes);
        } else if (columnNames != null) {
            ps = conn.prepareStatement(sql, columnNames);
        } else if (resultSetHoldability == -1) {
            ps = conn.prepareStatement(sql, this.resultSetType, this.resultSetConcurrency);
        } else {
            ps = conn.prepareStatement(sql, this.resultSetType, this.resultSetConcurrency,
                resultSetHoldability);
        }
        setBaseStatement(ps);
        if (queryTimeout >= 0) {
            ps.setQueryTimeout(queryTimeout);
        }
        ps.setFetchSize(fetchSize);
        ps.setMaxRows(maxRows);

        return ps;
    }

    public ResultSet executeQuery() throws SQLException {
        checkClosed();
        ensureResultSetIsEmpty();

        boolean gotoRead = SqlType.SELECT.equals(SQLParser.getSqlType(sql))
                           && tGroupConnection.getAutoCommit();
        Connection conn = tGroupConnection.getBaseConnection(sql, gotoRead);

        if (conn != null) {
            return executeQueryOnConnection(conn, sql);
        } else {
            return this.tGroupDataSource.getDBSelector().tryExecute(executeQueryTryer,
                this.getConsistency(sql, gotoRead), SQLHintParser.getCluster(sql), sql,
                this.parameterSettings);
        }
    }

    public boolean execute() throws SQLException {
        checkClosed();
        ensureResultSetIsEmpty();

        boolean gotoRead = SqlType.SELECT.equals(SQLParser.getSqlType(this.sql))
                           && tGroupConnection.getAutoCommit();
        Connection conn = tGroupConnection.getBaseConnection(sql, gotoRead);

        if (conn != null) {
            return executeOnConnection(conn);
        } else {
            return this.tGroupDataSource.getDBSelector().tryExecute(executeTryer,
                this.getConsistency(this.sql, gotoRead), SQLHintParser.getCluster(this.sql),
                this.sql, this.parameterSettings);
        }
    }

    protected DataSourceTryer<Boolean> executeTryer = new DataSourceTryer<Boolean>() {
                                                        public Boolean tryOnDataSource(DataSourceHolder dsw,
                                                                                       Object... args)
                                                                                                      throws SQLException {
                                                            Connection conn = TGroupPreparedStatement.this.tGroupConnection
                                                                .createNewConnection(dsw, false);
                                                            return executeOnConnection(conn);
                                                        }
                                                    };

    protected boolean executeOnConnection(Connection conn) throws SQLException {
        PreparedStatement ps = this.createPreparedStatementInternal(conn, this.sql);
        Parameters.setParameters(ps, this.parameterSettings);
        boolean result = ps.execute();
        this.currentResultSet = ps.getResultSet();
        this.updateCount = ps.getUpdateCount();
        return result;
    }

    @Override
    protected ResultSet executeQueryOnConnection(Connection conn, String sql) throws SQLException {
        PreparedStatement ps = this.createPreparedStatementInternal(conn, sql);
        Parameters.setParameters(ps, parameterSettings);
        this.currentResultSet = ps.executeQuery();
        return this.currentResultSet;
    }

    public int executeUpdate() throws SQLException {
        checkClosed();
        ensureResultSetIsEmpty();

        Connection conn = tGroupConnection.getBaseConnection(sql, false);

        if (conn != null) {
            //#bug 2011-10-28,modify by junyu,updateCount not set,fixed
            super.updateCount = executeUpdateOnConnection(conn);
            return super.updateCount;
        } else {
            //#bug 2011-10-28,modify by junyu,updateCount not set,fixed
            super.updateCount = tGroupDataSource.getDBSelector().tryExecute(executeUpdateTryer,
                true, SqlHintType.CLUSTER_NONE, sql, this.parameterSettings);
            return super.updateCount;
        }
    }

    private int executeUpdateOnConnection(Connection conn) throws SQLException {
        PreparedStatement ps = createPreparedStatementInternal(conn, sql);
        Parameters.setParameters(ps, parameterSettings);
        return ps.executeUpdate();
    }

    private DataSourceTryer<Integer> executeUpdateTryer = new DataSourceTryer<Integer>() {
                                                            public Integer tryOnDataSource(DataSourceHolder dsw,
                                                                                           Object... args)
                                                                                                          throws SQLException {
                                                                Connection conn = TGroupPreparedStatement.this.tGroupConnection
                                                                    .createNewConnection(dsw, false);
                                                                return executeUpdateOnConnection(conn);
                                                            }
                                                        };

    public ResultSetMetaData getMetaData() throws SQLException {
        throw new UnsupportedOperationException("getMetaData");
    }

    public ParameterMetaData getParameterMetaData() throws SQLException {
        throw new UnsupportedOperationException("getParameterMetaData");
    }

    public void setArray(int i, Array x) throws SQLException {
        parameterSettings.put(i, new ParameterContext(ParameterMethod.setArray,
            new Object[] { i, x }));
    }

    public void setAsciiStream(int parameterIndex, InputStream x, int length) throws SQLException {
        parameterSettings.put(parameterIndex, new ParameterContext(ParameterMethod.setAsciiStream,
            new Object[] { parameterIndex, x, length }));
    }

    public void setBigDecimal(int parameterIndex, BigDecimal x) throws SQLException {
        parameterSettings.put(parameterIndex, new ParameterContext(ParameterMethod.setBigDecimal,
            new Object[] { parameterIndex, x }));
    }

    public void setBinaryStream(int parameterIndex, InputStream x, int length) throws SQLException {
        parameterSettings.put(parameterIndex, new ParameterContext(ParameterMethod.setBinaryStream,
            new Object[] { parameterIndex, x, length }));
    }

    public void setBlob(int i, Blob x) throws SQLException {
        parameterSettings.put(i, new ParameterContext(ParameterMethod.setBlob,
            new Object[] { i, x }));
    }

    public void setBoolean(int parameterIndex, boolean x) throws SQLException {
        parameterSettings.put(parameterIndex, new ParameterContext(ParameterMethod.setBoolean,
            new Object[] { parameterIndex, x }));
    }

    public void setByte(int parameterIndex, byte x) throws SQLException {
        parameterSettings.put(parameterIndex, new ParameterContext(ParameterMethod.setByte,
            new Object[] { parameterIndex, x }));
    }

    public void setBytes(int parameterIndex, byte[] x) throws SQLException {
        parameterSettings.put(parameterIndex, new ParameterContext(ParameterMethod.setBytes,
            new Object[] { parameterIndex, x }));
    }

    public void setCharacterStream(int parameterIndex, Reader reader, int length)
                                                                                 throws SQLException {
        parameterSettings.put(parameterIndex, new ParameterContext(
            ParameterMethod.setCharacterStream, new Object[] { parameterIndex, reader, length }));
    }

    public void setClob(int i, Clob x) throws SQLException {
        parameterSettings.put(i, new ParameterContext(ParameterMethod.setClob,
            new Object[] { i, x }));
    }

    public void setDate(int parameterIndex, Date x) throws SQLException {
        parameterSettings.put(parameterIndex, new ParameterContext(ParameterMethod.setDate1,
            new Object[] { parameterIndex, x }));
    }

    public void setDate(int parameterIndex, Date x, Calendar cal) throws SQLException {
        parameterSettings.put(parameterIndex, new ParameterContext(ParameterMethod.setDate2,
            new Object[] { parameterIndex, x, cal }));
    }

    public void setDouble(int parameterIndex, double x) throws SQLException {
        parameterSettings.put(parameterIndex, new ParameterContext(ParameterMethod.setDouble,
            new Object[] { parameterIndex, x }));
    }

    public void setFloat(int parameterIndex, float x) throws SQLException {
        parameterSettings.put(parameterIndex, new ParameterContext(ParameterMethod.setFloat,
            new Object[] { parameterIndex, x }));
    }

    public void setInt(int parameterIndex, int x) throws SQLException {
        parameterSettings.put(parameterIndex, new ParameterContext(ParameterMethod.setInt,
            new Object[] { parameterIndex, x }));
    }

    public void setLong(int parameterIndex, long x) throws SQLException {
        parameterSettings.put(parameterIndex, new ParameterContext(ParameterMethod.setLong,
            new Object[] { parameterIndex, x }));
    }

    public void setNull(int parameterIndex, int sqlType) throws SQLException {
        parameterSettings.put(parameterIndex, new ParameterContext(ParameterMethod.setNull1,
            new Object[] { parameterIndex, sqlType }));
    }

    public void setNull(int paramIndex, int sqlType, String typeName) throws SQLException {
        parameterSettings.put(paramIndex, new ParameterContext(ParameterMethod.setNull2,
            new Object[] { paramIndex, sqlType, typeName }));
    }

    public void setObject(int parameterIndex, Object x) throws SQLException {
        parameterSettings.put(parameterIndex, new ParameterContext(ParameterMethod.setObject1,
            new Object[] { parameterIndex, x }));
    }

    public void setObject(int parameterIndex, Object x, int targetSqlType) throws SQLException {
        parameterSettings.put(parameterIndex, new ParameterContext(ParameterMethod.setObject2,
            new Object[] { parameterIndex, x, targetSqlType }));
    }

    public void setObject(int parameterIndex, Object x, int targetSqlType, int scale)
                                                                                     throws SQLException {
        parameterSettings.put(parameterIndex, new ParameterContext(ParameterMethod.setObject3,
            new Object[] { parameterIndex, x, targetSqlType, scale }));
    }

    public void setRef(int i, Ref x) throws SQLException {
        parameterSettings.put(i,
            new ParameterContext(ParameterMethod.setRef, new Object[] { i, x }));
    }

    public void setShort(int parameterIndex, short x) throws SQLException {
        parameterSettings.put(parameterIndex, new ParameterContext(ParameterMethod.setShort,
            new Object[] { parameterIndex, x }));
    }

    public void setString(int parameterIndex, String x) throws SQLException {
        parameterSettings.put(parameterIndex, new ParameterContext(ParameterMethod.setString,
            new Object[] { parameterIndex, x }));
    }

    public void setTime(int parameterIndex, Time x) throws SQLException {
        parameterSettings.put(parameterIndex, new ParameterContext(ParameterMethod.setTime1,
            new Object[] { parameterIndex, x }));
    }

    public void setTime(int parameterIndex, Time x, Calendar cal) throws SQLException {
        parameterSettings.put(parameterIndex, new ParameterContext(ParameterMethod.setTime2,
            new Object[] { parameterIndex, x, cal }));
    }

    public void setTimestamp(int parameterIndex, Timestamp x) throws SQLException {
        parameterSettings.put(parameterIndex, new ParameterContext(ParameterMethod.setTimestamp1,
            new Object[] { parameterIndex, x }));
    }

    public void setTimestamp(int parameterIndex, Timestamp x, Calendar cal) throws SQLException {
        parameterSettings.put(parameterIndex, new ParameterContext(ParameterMethod.setTimestamp2,
            new Object[] { parameterIndex, x, cal }));
    }

    public void setURL(int parameterIndex, URL x) throws SQLException {
        parameterSettings.put(parameterIndex, new ParameterContext(ParameterMethod.setURL,
            new Object[] { parameterIndex, x }));
    }

    @Deprecated
    public void setUnicodeStream(int parameterIndex, InputStream x, int length) throws SQLException {
        parameterSettings.put(parameterIndex, new ParameterContext(
            ParameterMethod.setUnicodeStream, new Object[] { parameterIndex, x, length }));
    }

    /* ======================================================================== *
     *                            executeBatch                                  *
     * ======================================================================== */
    private List<Map<Integer, ParameterContext>> pstArgs = null;

    public void addBatch() throws SQLException {
        if (pstArgs == null) {
            pstArgs = new LinkedList<Map<Integer, ParameterContext>>();
        }
        Map<Integer, ParameterContext> newArg = new HashMap<Integer, ParameterContext>(
            parameterSettings.size());
        newArg.putAll(parameterSettings);
        parameterSettings.clear();
        pstArgs.add(newArg);
    }

    public int[] executeBatch() throws SQLException {
        try {
            checkClosed();
            ensureResultSetIsEmpty();
            if (pstArgs == null || pstArgs.isEmpty()) {
                return new int[0];
            }
            Connection conn = tGroupConnection.getBaseConnection(sql, false);
            if (conn != null) {
                return executeBatchOnConnection(conn);
            } else {
                return tGroupDataSource.getDBSelector().tryExecute(executeBatchTryer, true,
                    SqlHintType.CLUSTER_NONE, sql, this.parameterSettings);
            }
        } finally {
            if (pstArgs != null) {
                pstArgs.clear();
            }
        }
    }

    private DataSourceTryer<int[]> executeBatchTryer = new DataSourceTryer<int[]>() {
                                                         public int[] tryOnDataSource(DataSourceHolder dsw,
                                                                                      Object... args)
                                                                                                     throws SQLException {
                                                             Connection conn = tGroupConnection
                                                                 .createNewConnection(dsw, false);
                                                             return executeBatchOnConnection(conn);
                                                         }
                                                     };

    private int[] executeBatchOnConnection(Connection conn) throws SQLException {
        PreparedStatement ps = createPreparedStatementInternal(conn, sql);
        for (Map<Integer, ParameterContext> parameterSettings : pstArgs) {
            setBatchParameters(ps, parameterSettings.values());
            ps.addBatch();
        }
        return ps.executeBatch();
    }

    private static void setBatchParameters(PreparedStatement ps,
                                           Collection<ParameterContext> batchedParameters)
                                                                                          throws SQLException {
        for (ParameterContext context : batchedParameters) {
            Parameters.parameterHandlers.get(context.getParameterMethod()).setParameter(ps,
                context.getArgs());
        }
    }

    public int getAutoGeneratedKeys() {
        return autoGeneratedKeys;
    }

    public void setAutoGeneratedKeys(int autoGeneratedKeys) {
        this.autoGeneratedKeys = autoGeneratedKeys;
    }

    public int[] getColumnIndexes() {
        return columnIndexes;
    }

    public void setColumnIndexes(int[] columnIndexes) {
        this.columnIndexes = columnIndexes;
    }

    public String[] getColumnNames() {
        return columnNames;
    }

    public void setColumnNames(String[] columnNames) {
        this.columnNames = columnNames;
    }

    public boolean isClosed() throws SQLException {
        throw new SQLException("not support exception");
    }

    public void setPoolable(boolean poolable) throws SQLException {
        throw new SQLException("not support exception");
    }

    public boolean isPoolable() throws SQLException {
        throw new SQLException("not support exception");
    }

    public <T> T unwrap(Class<T> iface) throws SQLException {
        throw new SQLException("not support exception");
    }

    public boolean isWrapperFor(Class<?> iface) throws SQLException {
        throw new SQLException("not support exception");
    }

    public void setRowId(int parameterIndex, RowId x) throws SQLException {
        throw new SQLException("not support exception");
    }

    public void setNString(int parameterIndex, String value) throws SQLException {
        throw new SQLException("not support exception");
    }

    public void setNCharacterStream(int parameterIndex, Reader value, long length)
                                                                                  throws SQLException {
        throw new SQLException("not support exception");
    }

    public void setNClob(int parameterIndex, NClob value) throws SQLException {
        throw new SQLException("not support exception");
    }

    public void setClob(int parameterIndex, Reader reader, long length) throws SQLException {
        throw new SQLException("not support exception");
    }

    public void setBlob(int parameterIndex, InputStream inputStream, long length)
                                                                                 throws SQLException {
        throw new SQLException("not support exception");
    }

    public void setNClob(int parameterIndex, Reader reader, long length) throws SQLException {
        throw new SQLException("not support exception");
    }

    public void setSQLXML(int parameterIndex, SQLXML xmlObject) throws SQLException {
        throw new SQLException("not support exception");
    }

    public void setAsciiStream(int parameterIndex, InputStream x, long length) throws SQLException {
        throw new SQLException("not support exception");
    }

    public void setBinaryStream(int parameterIndex, InputStream x, long length) throws SQLException {
        throw new SQLException("not support exception");
    }

    public void setCharacterStream(int parameterIndex, Reader reader, long length)
                                                                                  throws SQLException {
        throw new SQLException("not support exception");
    }

    public void setAsciiStream(int parameterIndex, InputStream x) throws SQLException {
        throw new SQLException("not support exception");
    }

    public void setBinaryStream(int parameterIndex, InputStream x) throws SQLException {
        throw new SQLException("not support exception");
    }

    public void setCharacterStream(int parameterIndex, Reader reader) throws SQLException {
        throw new SQLException("not support exception");
    }

    public void setNCharacterStream(int parameterIndex, Reader value) throws SQLException {
        throw new SQLException("not support exception");
    }

    public void setClob(int parameterIndex, Reader reader) throws SQLException {
        throw new SQLException("not support exception");
    }

    public void setBlob(int parameterIndex, InputStream inputStream) throws SQLException {
        throw new SQLException("not support exception");
    }

    public void setNClob(int parameterIndex, Reader reader) throws SQLException {
        throw new SQLException("not support exception");
    }

}
